/* Generated from Emperia-Server/protocol/realtime-contract.schema.json. */
/* Do not edit this file directly. */

export const PROTOCOL_SCHEMA_SHA256 = "30ff85405d30ed037a73c7e34011d728e76625c8bc07bdc95cd7f8be0e415208";

export const ITEM_SLOT_TYPES = [
  "head",
  "body",
  "legs",
  "feet",
  "left-hand",
  "right-hand",
  "hand",
  "two-handed",
  "ring",
  "necklace",
  "backpack",
  "belt",
  "ammo",
  "quiver",
  "rope",
  "shovel",
  "pick",
  "knife",
  "machete",
  "fishingRod",
  "potion",
  "food",
  "rune",
  "key",
] as const;
export type ItemSlotType = typeof ITEM_SLOT_TYPES[number];

export function encodeItemSlotType(slotType: string): number {
  const index = ITEM_SLOT_TYPES.indexOf(slotType as ItemSlotType);
  if (index < 0) throw new Error(`Unknown item slot type "${slotType}"`);
  return index + 1;
}

export function decodeItemSlotType(code: number): ItemSlotType {
  const slotType = ITEM_SLOT_TYPES[code - 1];
  if (!slotType) throw new Error(`Unknown item slot type code ${code}`);
  return slotType;
}
